apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-details-deployment
spec:
  selector:
    matchLabels:
      app: customer-details
      version: v01
  replicas: 2
  template:
    metadata:
      labels:
        app: customer-details
        version: v01
    spec:
      containers:
      - name: customer-details
        image: #aveek123456/argocd:1.1  -- need to be replaced
        ports:
        - containerPort: 80
        resources:
         limits: 
          cpu: 500m
          memory: 128Mi
         requests:
          cpu: 250m
          memory: 64Mi
        readinessProbe:
         tcpSocket:
          port: 80
         initialDelaySeconds: 15
         periodSeconds: 20 
        livenessProbe:
         httpGet:
          path: /
          port: 80
         initialDelaySeconds: 5
         periodSeconds: 30    